feat: add millisecond option to ser_json_timedelta
pydantic/pydantic pull request #10293
Opened 2024-09-03 08:55 UTC by ollz272

## Change Summary

Implements https://github.com/pydantic/pydantic/issues/10256 : adds a millisecond option to `ser_json_timedelta`. These are the changes needed in pydantic to enable the changes: see https://github.com/pydantic/pydantic-core/pull/1427 for the corrosponding pydantic core changes.

## Related issue number

fix #10256

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [x] Unit tests for the changes exist
* [ ] Tests pass on CI
* [x] Documentation reflects the changes where applicable
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

2024-09-03 08:56 UTC, ollz272 commented
Note that tests are not *yet* passing, but i've tested the new tests locally against the pydantic core changes and all looks good there. Just needs https://github.com/pydantic/pydantic-core/pull/1427 looked at and merged so this can get in.

2024-09-10 17:10 UTC, sydney-runkle requested changes
Looks good overall, though let's please:
* Update the docs
* Consider adding a `'second'` option, equivalent to `'float'` as mentioned. We could even deprecate `'float'` in v2 with `'second'` as the replacement.

Thanks for your contribution here!!

2024-09-10 17:10 UTC, sydney-runkle commented on pydantic/config.py
>      The format of JSON serialized timedeltas. Accepts the string values of `'iso8601'` and
Will need to change the docstring here.

I'm wondering if we should add support for `'second'` as well, and deprecate `'float'` down the line (equivalent to `'second'`...

2024-09-10 17:10 UTC, sydney-runkle commented
Maybe `'seconds'` and `'milliseconds'` makes more sense...

2024-09-10 17:10 UTC, sydney-runkle commented
Will get back to you re this API change tomorrow morning 👍 - need to get feedback from the team re official decision.

2024-09-10 17:19 UTC, ollz272 commented
> Will get back to you re this API change tomorrow morning 👍 - need to get feedback from the team re official decision.

Great thank you, changes on the pydantic core side should be straightforward if you wanna do this. I'll update the docs

2024-09-11 15:53 UTC, sydney-runkle commented
Verdict on the API - let's go with:

`iso8601`
`seconds_float`
`milliseconds_float`

For now. We'll need to add deprecation info / docs updates for the `float -> seconds_float` logic. This also provides us with the ability to add `seconds_int` and `milliseconds_int` down the line if that's a high enough demand feature request.

Thanks for your help on this - happy to do another review once you've made those changes!

2024-09-11 16:27 UTC, ollz272 commented
> Verdict on the API - let's go with:
> 
> `iso8601` `seconds_float` `milliseconds_float`
> 
> For now. We'll need to add deprecation info / docs updates for the `float -> seconds_float` logic. This also provides us with the ability to add `seconds_int` and `milliseconds_int` down the line if that's a high enough demand feature request.
> 
> Thanks for your help on this - happy to do another review once you've made those changes!

Would you like me to just add `seconds_int` and `milliseconds_int`? Wouldn't be too much extra work 😄

2024-09-11 17:33 UTC, ollz272 reviewed
Left some of my own comments explaining decisions.

2024-09-11 17:35 UTC, ollz272 commented
@sydney-runkle Hi!

Thanks for the response. I've now:

- Pinned this to my branch of pydantic core so tests can run in the pipeline properly
- Added seconds_float and milliseconds_float options
- Deprecated float, with docs and a warning
- Updated tests

Let me know if theres anything further you want me to do. And if you want me to add the int options, more than happy to just get this done 👍🏻 

Assigning back to you

2024-09-11 17:35 UTC, ollz272 commented
please review

2024-09-12 15:19 UTC, sydney-runkle requested changes
Nice work here! A couple of things:

* Let's fully deprecate `float` support - see comments above.
* Make sure that you're consistent with `seconds_float` vs `float_seconds`. I'd opt for the former.

DH had some good feedback on the `pydantic-core` end of things re multiplication with floats + performance.

Happy to do one more review here after you make the remaining changes.

2024-09-12 15:19 UTC, sydney-runkle commented on pydantic/config.py
> +        NOTE: `'float' is deprecated in favour of `'float_seconds'`
Let's list deprecated in v2.10

2024-09-12 21:50 UTC, davidhewitt commented on pydantic/_internal/_config.py
> +                'Using a `float` as an option for `ser_json_timedelta` is deprecated, use a `float_seconds` instead.',
We should continue to emit this warning, even if we remove "support". We can remove the coercion in v3, I think.

2024-09-13 10:43 UTC, ollz272 commented
Right, i've pushed changes related to comments made

I think probably not worth reviewing again until the `pydantic-core` changes are finished.

Only thing to note is there are some type checking errors happening, though i think they're caused by https://github.com/pydantic/pydantic-core/pull/1443

2024-09-13 14:38 UTC, sydney-runkle commented
@ollz272,

Sounds good, ping me when you're ready for a final review here.

Cc @Viicos re:

> Only thing to note is there are some type checking errors happening, though i think they're caused by https://github.com/pydantic/pydantic-core/pull/1443

2024-09-18 14:09 UTC, sydney-runkle commented on pyproject.toml
> +    "pydantic-core @ git+https://github.com/ollz272/pydantic-core@add-millisecond",
@ollz272, could you revert this change as well as the `pdm.lock` changes? Thanks!

2024-09-18 14:21 UTC, sydney-runkle requested changes
Looking great - just a few minor change requests, otherwise, we should be ready to merge!

I have some changes that I'd like to make to `pydantic-core` in the next week, so might wait for that to do the minor release with your changes.

2024-09-18 14:21 UTC, sydney-runkle commented on pydantic/config.py
> +    ser_json_timedelta: Literal['iso8601', 'milliseconds_float', 'seconds_float']
```suggestion
    ser_json_timedelta: Literal['iso8601', 'seconds_float', 'milliseconds_float']
```

Nit pick, let's keep the order the same as that of `pydantic-core`

2024-09-18 14:21 UTC, sydney-runkle commented on pydantic/config.py
> +    'seconds_float'`, `'float_milliseconds'` and `'float'`. Defaults to `'iso8601'`.
Should read:

```
The format of JSON serialized timedeltas. Accepts the string values of `'iso8601'`, `'seconds_float'`, and `'milliseconds_float'`. Defaults to `'iso8601'`.
```

2024-09-18 14:21 UTC, sydney-runkle commented on tests/test_json_schema.py
> +def test_model_default_timedelta(
Yeah, I think having their own tests would be good so that we can avoid the conditional warning checks.

2024-09-18 14:35 UTC, ollz272 commented
> Looking great - just a few minor change requests, otherwise, we should be ready to merge!
> 
> I have some changes that I'd like to make to `pydantic-core` in the next week, so might wait for that to do the minor release with your changes.

Makes sense, i think the only reason the docs ci is failing is because its not on a release of pydantic core. I'll fix up those points now. Happy to then change the version of pydantic core this points at, or for you guys to do it when you're ready for the pydantic core release.

2024-09-18 15:18 UTC, sydney-runkle commented
> Happy to then change the version of pydantic core this points at, or for you guys to do it when you're ready for the pydantic core release.

We can do this! If you could revert the `pdm.lock` and version changes though, that'd be great. Thanks!

2024-09-18 16:03 UTC, ollz272 commented
@sydney-runkle Hi!

Thanks, i've made your requested changes. Tests were still passing when i checked.

I've reverted the pyproject.toml and pdm.lock changes, so should be a simple change when you're ready.

Anything else let me know!

2024-09-19 13:21 UTC, sydney-runkle approved these changes
Amazing work here. Looking forward to this change.

I'll try to get a `pydantic-core` release out this week so that we can push this across the line.

2024-09-20 17:16 UTC, sydney-runkle commented
cc @ollz272, all set to merge :)

2024-09-20 17:24 UTC, merged