Fix str description and add references
pydantic/pydantic pull request #10676
Opened 2024-10-21 18:06 UTC by mschoettle

## Change Summary

Replace the backtick with an apostrophe since the rendered output is broken.

Add references to the Python documentation for str, bytes, bytearray, bytes.decode, and Enum.value.

## Related issue number

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI
* [ ] Documentation reflects the changes where applicable
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

2024-10-21 18:27 UTC, mschoettle commented
please review

(the typechecking job failure is unrelated)

2024-10-21 18:57 UTC, mschoettle commented
> (the typechecking job failure is unrelated)

Fixed in #10677

2024-10-21 19:26 UTC, Viicos requested changes
Thanks!

2024-10-21 19:26 UTC, Viicos commented on docs/api/standard_library_types.md
> +[`str`][]: Strings are accepted as-is. [`bytes`][] and [`bytearray`][] are converted using [`v.decode()`](https://docs.python.org/3/library/stdtypes.html#bytes.decode).
```suggestion
[`str`][]: Strings are accepted as-is. [`bytes`][] and [`bytearray`][] are converted using the [`decode()`][bytes.decode] method.
```

2024-10-21 19:26 UTC, Viicos commented on docs/api/standard_library_types.md
> +Enums inheriting from `str` are converted using [`v.value`](https://docs.python.org/3/library/enum.html#enum.Enum.value). All other types cause an error.
```suggestion
Enums inheriting from [`str`][] are converted the [`value`][enum.Enum.value] attribute. All other types cause an error.
```

2024-10-21 20:51 UTC, mschoettle commented
Thanks! It wasn't clear if the commits in the PR are squashed at the end (could not find this information in the contribution guide) but based on the other PR I now see that it is. That's why I didn't apply the suggestions, will do that in the future.

I also separated the remaining two sentences on separate lines.

2024-10-22 07:20 UTC, Viicos commented on docs/api/standard_library_types.md
> +All other types cause an error.
```suggestion
- [`str`][]: Strings are accepted as-is.
- [`bytes`][] and [`bytearray`][] are converted using the [`decode()`][bytes.decode] method.
- Enums inheriting from [`str`][] are converted using the [`value`][enum.Enum.value] attribute.

All other types cause an error.
```

2024-10-22 07:20 UTC, Viicos approved these changes

2024-10-22 07:26 UTC, merged