ci: Third party test for beanie
pydantic/pydantic pull request #11177
Opened 2024-12-24 05:01 UTC by mdaffad

## Change Summary

Integrate beanie tests on third party test workflow, part of third party tests on #11160

## Related issue number

#11160

## Checklist

* [ ] The pull request title is a good summary of the changes - it will be used in the changelog
* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI
* [ ] Documentation reflects the changes where applicable
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

2024-12-24 12:46 UTC, Viicos requested changes
Thanks for the PR. This looks great

2024-12-24 12:46 UTC, Viicos commented on .github/workflows/third-party.yml
> +        mongodb-version: ${{ matrix.mongodb-version }}
```suggestion
        mongodb-version: '8.0'
```

Let's test against a single MongoDB version.

2024-12-24 12:46 UTC, Viicos commented on .github/workflows/third-party.yml
> +        mongodb-version: [4.4, 5.0, 6.0, 7.0, 8.0 ]
```suggestion
```

2024-12-24 12:46 UTC, Viicos commented on .github/workflows/third-party.yml
> +        python-version: ${{ matrix.python-version }}
```suggestion
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
```

Best to be as close to the project's CI.

2024-12-24 12:46 UTC, Viicos commented on .github/workflows/third-party.yml
> +    - name: Checkout beanie
```suggestion
    - name: Checkout Beanie
```

2024-12-24 12:46 UTC, Viicos commented on .github/workflows/third-party.yml
> +        uv pip install ./pydantic-latest
```suggestion
    - name: Install Beanie dependencies
      run: |
        pip install .[test,ci]
        pip uninstall --yes pydantic 
        pip install ./pydantic-latest
```

2024-12-24 12:46 UTC, Viicos commented on .github/workflows/third-party.yml
> +        PYTHON_JIT: 1
```suggestion
    - name: Run Beanie tests
```

2024-12-27 16:07 UTC, sydney-runkle commented on .github/workflows/third-party.yml
> +
```suggestion

```

2024-12-27 16:12 UTC, sydney-runkle commented
LGTM, let's wait for @Viicos' approval before we merge :)

2024-12-28 09:42 UTC, Viicos approved these changes
Thanks!

2024-12-28 09:42 UTC, merged