New type StrLimited
pydantic/pydantic pull request #3724
Opened 2022-01-23 13:16 UTC by lucastosetto

## Change Summary

This represents a simplified length limited string and is an alias for the following syntax:

`StrLimited[max_length]` = `constr(max_length=max_length, strip_whitespace=True)`

Usage example:

```
class Foo:
    bar: StrLimited[10] # bar is a str with maximum length of 10 characters
```

## Related issue number

fix #2104

## Checklist

* [x] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable
* [x] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

2022-01-23 13:26 UTC, lucastosetto commented
please review

2022-04-02 14:11 UTC, samuelcolvin reviewed
Looking good, will need to be added to docs.

2022-04-02 14:11 UTC, samuelcolvin commented on changes/2104-lucastosetto.md
> +Added simplified length limited string type, declared as StrLimited[max_length].
```suggestion
Added simplified length limited string type, declared as `StrLimited[max_length]`.
```

2022-04-02 14:11 UTC, samuelcolvin commented on pydantic/types.py
> +    def __class_getitem__(cls, max_length: int) -> Type[str]:
```suggestion
    def __class_getitem__(cls, max_length: int) -> Type[ConstrainedStr]:
```

2022-04-02 14:11 UTC, samuelcolvin commented on pydantic/types.py
> +class StrLimited:
you might want to implement `__get_validators__` and raise an error people try to use `StrLimited` with parameterising it.

2022-04-02 14:11 UTC, samuelcolvin commented on tests/test_types.py
> +        v: StrLimited[max_length]
cleanest to hard code the length
```suggestion
        v: StrLimited[5]
```

2022-04-02 14:11 UTC, samuelcolvin commented on tests/test_types.py
> +    m = Model(v='abcde')
```suggestion
    m = Model(v='abcde ')
```
show that it also strips white space.

2022-04-02 14:11 UTC, samuelcolvin commented on tests/test_types.py
> +        v: StrLimited[max_length]
```suggestion
        v: StrLimited[5]
```
same, always best to hard code tests unless you need to vary the value, which you don't here.

2022-04-02 14:11 UTC, samuelcolvin commented on pydantic/types.py
> +    def __class_getitem__(cls, max_length: int) -> Type[str]:
We could also be clever and allow slice usage:

```py
class MyModel(BaseModel):
    has_max_length: StrLimited[10]
    has_min_and_max_length: StrLimited[5:10]
```

WDYT?

2022-04-02 14:11 UTC, samuelcolvin commented
please update.

2022-08-08 13:04 UTC, samuelcolvin requested changes
Looking good, but a few other things still to do:
* `__get_validators__` as suggested above
* add docs, as suggested above

2022-08-08 13:04 UTC, samuelcolvin commented on tests/test_types.py
> +    max_length = 5
you can remove this, it's not used.

2022-08-08 13:04 UTC, samuelcolvin commented on tests/test_types.py
> +    max_length = 5
you can remove this and just use a hard-coded value below, it's not adding anything.

2022-08-12 14:10 UTC, samuelcolvin commented
@lucastosetto any chance you can fix this?

2022-08-19 09:14 UTC, samuelcolvin commented
See [twitter :bird:](https://twitter.com/pydantic/status/1560554679473303552), I've you'd like this to be included in V1.10, please fix it and request a review **TODAY**.

Or if you need this in V1.10 but don't have time to complete it (or aren't the author), please comment here and on #4324

2022-08-21 15:05 UTC, cloudwalk-tests commented
> @lucastosetto any chance you can fix this?

@samuelcolvin Sure, I can work on it this week, but I won't have time to do this for v1.10

2022-08-21 15:07 UTC, lucastosetto commented
> @lucastosetto any chance you can fix this?

Sure, I can work on it this week, but I won't have time to do it for v1.10 release.

2022-08-21 15:11 UTC, samuelcolvin commented
Ok, I might try to finish it for you.

If it doesn't make it into v1.10 much of the implementation will have to change for V2.

2022-08-22 12:58 UTC, samuelcolvin commented
> Ok, I might try to finish it for you.

Ignore that, I'm not going to have time to work on this, I think it'll have to wait for V2.

2022-08-28 12:08 UTC, antonagestam commented on pydantic/types.py
> +        return constr(max_length=max_length, strip_whitespace=True)
This usage of `__class_getitem__` isn't compatible with typing, at least mypy will give an error for `StrLimited[10]`, and I believe the other major type checkers would too. Mypy gives: `error: The type "Type[StrLimited]" is not generic and not indexable [misc]`. I'd suggest redesigning this to make `StrLimited` an object that implements `__get_item__` instead.

2023-03-09 09:41 UTC, closed without merging