Generate JSON schema for Sequence[T] as though it was List[T]
pydantic/pydantic pull request #5706
Opened 2023-05-06 20:16 UTC by dmontagu

Closes #5597

@lig would you mind adding any tests you think are appropriate here out of PR https://github.com/pydantic/pydantic/pull/5598? If this addresses all of those (and we merge this), maybe close that PR as well.

2023-05-06 20:16 UTC, dmontagu commented
please review

2023-05-07 13:08 UTC, lig commented
I've added a test https://github.com/pydantic/pydantic/blob/f27f0944186c6aca1e296d0eadd196f7387370d7/tests/test_json_schema.py#L3764 and it is failing 🤷🏻‍♂️

2023-05-08 13:36 UTC, dmontagu commented
please update (mentioning for myself :)

2023-05-15 13:11 UTC, lig requested changes

2023-05-15 13:11 UTC, lig commented on pydantic/_internal/_generate_schema.py
>              )
Personally, I would understand this code better if it looked something like this
```py
        list_schema = core_schema.list_schema(self.generate_schema(item_type), allow_any_iter=True)
        python_schema = core_schema.is_instance_schema(typing.Sequence, cls_repr='Sequence')
        if item_type != Any:
            from ._validators import sequence_validator
            python_schema = core_schema.chain_schema(
                [
                    python_schema,
                    core_schema.no_info_wrap_validator_function(sequence_validator, list_schema),
                ],
            )
```
As for me this way it explains it's meaning better

2023-05-15 13:31 UTC, lig commented
please update :)

2023-05-15 18:48 UTC, merged