Add documentation for strict mode
pydantic/pydantic pull request #6196
Opened 2023-06-20 14:09 UTC by tpdorsey

Adds documentation and examples for strict validation mode

## Change Summary

- New Strict Mode page
- Strict mode sections in Models, Model Config, and Fields
- Updated docstrings with references to Strict Mode usage docs

## Related issue number

Closes PYD-91

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable
* [ ] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @dmontagu

2023-06-20 14:26 UTC, tpdorsey commented
Please review

2023-06-21 06:57 UTC, Kludex requested changes

2023-06-21 06:57 UTC, Kludex commented on docs/usage/conversion_table.md
> +"Lax mode" indicates the default behavior of Pydantic, where it attempts to coerce values to the correct type, when possible. "Strict mode" indicates the behavior of Pydantic when `strict=True` is se
```suggestion
"Lax mode" indicates the default behavior of Pydantic, where it attempts to coerce values to the correct type, when possible. "Strict mode" indicates the behavior of Pydantic when `strict=True` is set on either a field or on a model config.
```

2023-06-21 06:57 UTC, Kludex commented on docs/usage/models.md
> +## Strict Mode
I think this is the perfect place to talk about the "Strict Mode".

2023-06-21 06:57 UTC, Kludex commented on docs/usage/strict_mode.md
> +There are some situations where you want Pydantic to throw an error instead of coercing data.
I don't think this file will fit well in the current organization. The section on the `models.md` about the Strict Mode that you added in this PR is great already.

2023-06-21 12:07 UTC, Kludex commented
The Strict Types are being explained on the `number_types.md` file. That may not be the best place for it.

Shall we include it with the "Strict Mode", or create a `strict_types.md` on the `Types` files?

2023-06-21 13:40 UTC, tpdorsey commented
@Kludex revised per your comments, please re-check

2023-06-21 17:25 UTC, Kludex approved these changes
> Shall we include it with the "Strict Mode", or create a strict_types.md on the Types files?

So, no? 🤔

2023-06-21 17:33 UTC, tpdorsey commented
@Kludex I think strict types is its own thing. I'll submit a separate PR for that.

2023-06-21 19:24 UTC, merged