replace_types config option
pydantic/pydantic pull request #6535
Opened 2023-07-08 21:23 UTC by vitalik

## Change Summary

## Related issue number

Fixes #6045

Introduced new config option `replace_types` that allows to patch fields annotations after class creation:

```Python
LaxStr = Annotated[str, BeforeValidator(str_validator)]

class LaxStrBase(BaseModel):
    model_config: ConfigDict = {'replace_types': {str: LaxStr}} # !!!!!!!!!

class Data(LaxStrBase):
    f: str
    i: str
    d: str

user = Data(f=1.1, i=1, d=Decimal('1.1'))
# will equal to {'f': '1.1', 'i': '1', 'd': '1.1'}
```

this also allows a pydantic global override string behaviour:
```Python
BaseModel.model_config['replace_types'] = {str: LaxStr}
```

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable
* [ ] `changes/<pull request or issue id>-<github username>.md` file added describing change
  (see [changes/README.md](https://github.com/samuelcolvin/pydantic/blob/master/changes/README.md) for details)
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

2023-07-08 21:38 UTC, adriangb commented
I like this idea! My main concern is the implementation, in particular, that it is done by replacing fields and only for BaseModel. It seems to me like it could be made to work for dataclasses and typeddict without much more effort.

2023-07-08 21:46 UTC, vitalik commented
> replacing fields and only for BaseModel.

not sure I understand... - it should work for global (BaseModel), some base model (and only child classes) and a single class:

```Python

# 1 this changes globally
BaseModel.model_config['replace_types'] = {str: LaxStr}

# 2 this changes types only for child classes inherited from LaxStrBase

class LaxStrBase(BaseModel):
    model_config: ConfigDict = {'replace_types': {str: LaxStr}} 

# 3 and for one single model:

class MyModel(BaseModel):
    model_config: ConfigDict = {'replace_types': {str: LaxStr}} 
    a: str
    b: str
    x: OtherStr

```

2023-07-08 21:53 UTC, adriangb commented
I mean:

```python
from typing_extensions import TypedDict
from pydantic import ConfigDict
from pydantic.dataclasses import dataclass

@dataclass
class Model1:
    x: str
    __pydantic_config__ = ConfigDict(replace_types={str: int})

class Model2(TypedDict):
    x: str
    __pydantic_config__ = ConfigDict(replace_types={str: int})
```

2023-07-08 21:56 UTC, adriangb commented
A couple more things to think about:

- Handling generic types (`replace_types={List: Dict}`), how can users handle replacing the origin vs. replacing a parametrized version
- Recursive replacements, both that `{str: Annotated[str, ...]}` should cause recursive replacement and that `{str: int, int: float}` should (or not?) lead to `str` being replaced with `float`.

2023-07-08 23:16 UTC, vitalik commented
> * Handling generic types (`replace_types={List: Dict}`), how can users handle replacing the origin vs. replacing a parametrized version

I do not see any practicality in such a case, but even if it used - it will not replace concrete annotation with origins because the equal statement is used, and it will not work for cases without passed origins:

```
List != List[str]
List != List[Any]
str != Annotated[str, 'meta']
ans so on
```

> * Recursive replacements, both that `{str: Annotated[str, ...]}` should cause recursive replacement and that `{str: int, int: float}` should (or not?) lead to `str` being replaced with `float`.

Again - practicality is questionable, but yeah why not let user loop all the way `str -> int -> float` for some unknown reason (just keep keys of the dict in a required sort order)

I think the main practicality here is in enhancing types with extra Annotated markers or dates with datetimes with timezones. I do not see any useful case where you replace all your strings with integers or any other unrelated to each other types.

I guess if you really need some magic with handling container types and origins - the `replace_types` can be a callback function that takes class and FieldInfo and patches is it in any imaginable way:


```Python

def patch_strings(cls: BaseModel, field_name: str, info: FieldInfo):
    if info.annotation == str or info.annotation.origin == str:
         info.annotation = LaxStr
         info.summary = 'it can take numbers ;)'
    if name == 'age':
         info.annotation = Annotated[int, Range(0, 100)]

class LaxStrBase(BaseModel):
    model_config: ConfigDict = { 'replace_types': patch_strings }
```

2023-07-09 17:49 UTC, adriangb commented
Thanks for thinking about these things. I agree these aren't dealbreakers for the feature, I just wanted us to think about them a bit, thank you for keeping the focus on the core use cases this is solving. Practically speaking I see the value in this and think it'd be totally okay to start with no generics or recursive replacement support. I do think we need to get this to work with `TypedDict`, `dataclasses` at least, those two can also have a `Config`. Do you want to give that a shot?

2023-07-09 19:05 UTC, ybressler requested changes
I really love the implementation here. Offered some small code suggestions with your tests.

Code aside, I wonder if this change is in alignment with the direction of Pydantic V2. I personally really like this feature and would use it myself. But I am curious to see what the core contributors' take is on this.

2023-07-09 19:05 UTC, ybressler commented on tests/test_config.py
> +    assert user.model_dump() == {'f': '1.1', 'i': '1', 'd': '1.1'}
Consider parameterizing this test case – I would expect to see test examples for Nonetypes – ex, `None, 0, 'nan'`.

2023-07-09 19:05 UTC, ybressler commented on tests/test_config.py
> +        model_config = {'replace_types': {str: LaxStr}}
Interesting. Is this the behavior for other config settings? That they don't bubble down? If so, perhaps add this to the test docstring.

Also, would be helpful to create a ticket for documenting this behavior as follow up work (just so this doesn't get lost in the mix).

2023-07-14 13:38 UTC, vitalik commented
@adriangb back from #6045 

I think patching FieldInfo.annotation might not perfect - I'm trying to  do monkey patching on other large project but stuck with this:

```Python
from pydantic import BaseModel, Field, BeforeValidator
from typing import Annotated
from pydantic.v1.validators import str_validator
from pydantic._internal import _fields
from pydantic._internal import _model_construction


LaxStr = Annotated[str, BeforeValidator(str_validator)]

# patching orig_collect_model_fields

orig_collect_model_fields = _fields.collect_model_fields


def patched_collect_model_fields(*a, **kw):
    fields, classvars = orig_collect_model_fields(*a, **kw)
    for f in fields.values():
        if f.annotation == str:
            f.annotation = LaxStr
    return fields, classvars


_model_construction.collect_model_fields = patched_collect_model_fields


class Data(BaseModel):
    gender: str = Field('F', max_length=1)


print(Data(gender='M'))

```

gives:
```
gender
  Value should have at most 1 item after validation, not 1 [type=too_long, input_value='M', input_type=str]
    For further information visit https://errors.pydantic.dev/2.0.3/v/too_long
```
probably some extra thing need to be done ?

2023-07-14 13:53 UTC, adriangb commented
Indeed that does seem brittle. I think this needs to happen during core schema generation.

2023-07-17 11:52 UTC, lig commented
@vitalik is this PR still on progress or it's ready for review?

2023-07-17 11:53 UTC, adriangb commented
I think it may still need some work but primarily it requires our input

2023-07-25 11:37 UTC, samuelcolvin commented
closing as we're working on another solution.

2023-07-25 11:37 UTC, closed without merging

2023-08-24 06:33 UTC, fortzi commented
@samuelcolvin can you please share what's planned to solve this issue?