Fix error message for staticmethod/classmethod order with validate_call
pydantic/pydantic pull request #6686
Opened 2023-07-14 18:36 UTC by dmontagu

closes https://github.com/pydantic/pydantic/issues/5329

2023-07-14 18:37 UTC, dmontagu commented on pydantic/validate_call.py
> +            )
```suggestion
        if isinstance(function, (classmethod, staticmethod)):
            name = type(function).__name__
            raise TypeError(
                f'The `@classmethod` decorator should be applied after `@{name}` (put `@{name}` on top)'
            )
```
Could do this instead, not sure which is preferable.

2023-07-14 18:38 UTC, dmontagu commented
please review

2023-07-18 09:05 UTC, samuelcolvin approved these changes
If that passes, LGTM.

2023-07-24 19:42 UTC, samuelcolvin requested changes
tests failing.

2023-07-25 14:15 UTC, dmontagu commented
please review

2023-07-25 14:42 UTC, merged

2023-07-25 14:42 UTC, samuelcolvin commented
TYVM