Raise an Error When Computed Field Overrides Field
pydantic/pydantic pull request #7346
Opened 2023-09-05 19:42 UTC by sydney-runkle

## Change Summary
* If a `computed_field` is defined in a subclass such that it overrides a field from a super class, a `ValueError` is raised.

## Related issue number

fix #7250 

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI
* [x] Documentation reflects the changes where applicable
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

2023-09-05 20:23 UTC, adriangb commented on tests/test_computed_fields.py
> +    assert e.value.args == ("you can't override a field with a computed field",)
```suggestion
    with pytest.raises(ValueError, match='you can't override a field with a computed field') as e:

        class SubModel(Model):
            @computed_field
            @property
            def name(self) -> str:
                return 'bar'
```

2023-09-05 20:23 UTC, adriangb requested changes

2023-09-05 20:23 UTC, adriangb commented on tests/test_computed_fields.py
> +    assert e.value.args == ("you can't override a field with a computed field",)
```suggestion
    with pytest.raises(ValueError, match='you can't override a field with a computed field') as e:

        class SubModel(Model):
            @computed_field
            @property
            def name(self) -> str:
                return 'bar'
```

2023-09-05 20:31 UTC, adriangb approved these changes
Approving since this error is at least less confusing than the current behavior. We can continue the discussion in https://github.com/pydantic/pydantic/issues/7250 if erroring doesn't seem like an acceptable approach.

2023-09-05 20:38 UTC, merged

2024-03-26 09:16 UTC, silky commented
It's moderately unfortunate that this behaviour is not available when it _is_ available with pure dataclasses (despite the mypy warning.)

Is there any thoughts of a work-around? I.e. to override an inheritied property; with a computed field or otherwise?