Removing booleans.md
pydantic/pydantic pull request #7408
Opened 2023-09-11 16:54 UTC by sydney-runkle

## Change Summary

Removing `booleans.md` file and moving content to new `standard_library_types.md` file.

## Related issue number

Contributing to #7322

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI
* [x] Documentation reflects the changes where applicable
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

2023-09-11 19:42 UTC, sydney-runkle commented
please review

2023-09-12 07:24 UTC, Kludex requested changes
Just a comment. Everything else looks good. :)

2023-09-12 07:24 UTC, Kludex commented on docs/usage/types/standard_types.md
Can we revert the changes in this file? 🤔 

(besides the boolean link change)

2023-09-12 07:25 UTC, Kludex commented
please update

2023-09-12 13:45 UTC, Kludex approved these changes

2023-09-12 13:55 UTC, merged