Adding SQLiteDsn Type
pydantic/pydantic pull request #7571
Opened 2023-09-22 18:52 UTC by sydney-runkle

## Change Summary

Adding support for `SQLiteDsn` type

## Related issue number

Fix #7515 

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [x] Unit tests for the changes exist
* [x] Tests pass on CI
* [x] Documentation reflects the changes where applicable
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

2023-09-22 18:53 UTC, sydney-runkle commented on pydantic/networks.py
> +]
Does this make sense? As far as I understand, you just need a file name connect to a SQLite database, so this case doesn't mirror the other `Dsn` types we support.

2023-09-22 18:54 UTC, sydney-runkle commented on tests/test_networks.py
> +
Happy to change how we're testing this if we don't want to include a dummy db file in a new `mocks` folder.

2023-09-22 18:58 UTC, sydney-runkle commented
please review

2023-09-22 19:04 UTC, sydney-runkle commented
Currently working on fixing tests + adding new test cases...

2023-09-25 14:00 UTC, adriangb requested changes

2023-09-25 15:32 UTC, adriangb commented on pydantic/networks.py
> +        raise PydanticCustomError('file_type_not_valid', 'SQLiteDsn file name must end in `.db`')
Why not `if not re.match(...):`?

2023-09-25 16:27 UTC, sydney-runkle commented on pydantic/networks.py
> +        raise PydanticCustomError('file_type_not_valid', 'SQLiteDsn file name must end in `.db`')
No reason - changed, thanks!

2023-09-25 16:37 UTC, adriangb requested changes
Can you provide a source on why the file extension is what we are validating? How standard is this file extension? Does SQLite just not work if it’s anything else?

2023-09-25 16:37 UTC, adriangb commented on tests/mocks/test_not_db
I’m confused as to why we need these. It’s not validating that the file actually exists, right?

2023-09-25 16:39 UTC, sydney-runkle commented on tests/mocks/test_not_db
Defining the type as an annotation of `FilePath` does validate that the file actually exists - is this not behavior that we want to include?

2023-09-25 16:40 UTC, sydney-runkle commented
> Can you provide a source on why the file extension is what we are validating? How standard is this file extension? Does SQLite just not work if it’s anything else?

Yeah, I think I misunderstood. These [sqlite docs](https://www.sqlite.org/shortnames.html) seem to suggest that other file types might work.

2023-09-25 16:41 UTC, sydney-runkle commented
> > Can you provide a source on why the file extension is what we are validating? How standard is this file extension? Does SQLite just not work if it’s anything else?
> 
> Yeah, I think I misunderstood. These [sqlite docs](https://www.sqlite.org/shortnames.html) seem to suggest that other file types might work.

[More confirmation of this](https://www.sqlite.org/appfileformat.html#:~:text=Single%2DFile%20Documents.&text=SQLite%20does%20not%20have%20any,%22belonging%22%20to%20the%20application.)

2023-09-25 16:49 UTC, adriangb commented on tests/mocks/test_not_db
Hmm I’m not sure. I can see a scenario where you’re just proxying some data from one place to another and don’t necessarily care if the files exist or not. I’m inclined to have the options for both. Maybe `SQLiteFile` and `ConcreteSQLiteFile` or similar. @samueldeklund wdyt?

2023-09-25 16:51 UTC, adriangb commented
If SQLite works with any file extension I feel that this is too under specified for us to create a type for it. Do we have a general “any file with this given extension” type? I imagine it’d have to use Annotated.

2023-09-25 16:57 UTC, sydney-runkle commented
> If SQLite works with any file extension I feel that this is too under specified for us to create a type for it. Do we have a general “any file with this given extension” type? I imagine it’d have to use Annotated.

We can easily annotate `Path` or `FilePath` with custom validators + get this effect, so I'd agree that it's too underspecified to merit a new type. Closing...

2023-09-25 16:57 UTC, closed without merging

2023-09-25 17:22 UTC, samueldeklund commented on tests/mocks/test_not_db
> Hmm I’m not sure. I can see a scenario where you’re just proxying some data from one place to another and don’t necessarily care if the files exist or not. I’m inclined to have the options for both. Maybe `SQLiteFile` and `ConcreteSQLiteFile` or similar. @samueldeklund wdyt?

I assume you meant to tag @samuelcolvin?

2023-09-25 17:23 UTC, adriangb commented on tests/mocks/test_not_db
Yes apologies