Keep values of private attributes set within `model_post_init` in subclasses
pydantic/pydantic pull request #7775
Opened 2023-10-09 12:28 UTC by alexmojaki

## Change Summary

Check for an existing `__pydantic_private__` dict in `init_private_attributes` and account for values within, rather than always replacing with a new dict.

## Related issue number

Fixes https://github.com/pydantic/pydantic/issues/7091

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [x] Unit tests for the changes exist
* [x] Tests pass on CI
* [x] Documentation reflects the changes where applicable
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @sydney-runkle

2023-10-09 12:56 UTC, alexmojaki commented
please review

2023-10-11 13:10 UTC, sydney-runkle requested changes
Looks good otherwise 👍 just a small change request

2023-10-11 13:10 UTC, sydney-runkle commented on pydantic/_internal/_model_construction.py
>          default = private_attr.get_default()
For simplicity, can we change this to
```py
if getattr(self, '__pydantic_private__', None) is None:
   pydantic_private={}
   ...
```

2023-10-11 13:10 UTC, sydney-runkle commented
@dmontagu did you have a test change you wanted to add?

2023-10-11 17:44 UTC, sydney-runkle approved these changes
LGTM, thanks so much for this contribution 🌟.

2023-10-11 17:48 UTC, sydney-runkle commented
Note to myself, when I work on the #7656 task, I want to add a more robust test for this behavior.

2023-10-11 17:48 UTC, merged