Make generic TypeAliasType specifications produce different schema definitions
pydantic/pydantic pull request #7893
Opened 2023-10-21 14:06 UTC by alexdrydew

## Change Summary

This PR fixes #7840: now different specifications of a generic TypeAliasType produce different definitions in pydantic schema which prevents "overwrites" of other specifications with the same origin.

## Related issue number

* Fix #7840 

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [x] Unit tests for the changes exist
* [x] Tests pass on CI
* [x] Documentation reflects the changes where applicable
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

2023-10-21 15:13 UTC, alexdrydew commented
please review

2023-10-25 19:32 UTC, sydney-runkle requested changes
LGTM overall, left a few nit picky change requests.

Thanks for the contribution ⭐!!

2023-10-25 20:04 UTC, dmontagu commented on pydantic/_internal/_typing_extra.py
> +        return isinstance(type_, typing._GenericAlias)  # type: ignore
```suggestion
if sys.version_info >= (3, 10):
    def is_generic_alias(type_: type[Any]) -> bool:
        return isinstance(type_, (types.GenericAlias, typing._GenericAlias))  # type: ignore[attr-defined] 
else:
    def is_generic_alias(type_: type[Any]) -> bool:
        return isinstance(type_, typing._GenericAlias)  # type: ignore
```
Super minor, but eliminates a runtime branch 🤷‍♂️

2023-10-25 20:05 UTC, dmontagu commented on tests/test_type_alias_type.py
> +@pytest.mark.xfail(sys.version_info >= (3, 12), reason="TypeAliasType doesn't have __qualname__ yet")
It fails for python _newer_ than (or equal to) 3.12? Saying "doesn't have qualname yet" makes me think the failure would happen for older-than-3.12, not 3.12 or newer.

Could you explain what's going wrong in a bit more detail?

2023-10-25 20:19 UTC, dmontagu commented on tests/test_type_alias_type.py
> +@pytest.mark.xfail(sys.version_info >= (3, 12), reason="TypeAliasType doesn't have __qualname__ yet")
Nevermind I see this was just copying what existing tests were doing

2023-10-25 20:24 UTC, dmontagu commented on tests/test_type_alias_type.py
> +@pytest.mark.xfail(sys.version_info >= (3, 12), reason="TypeAliasType doesn't have __qualname__ yet")
I see a way to resolve the need for these xfails, but I think that should be done in a separate PR, so ignore this comment.

2023-10-25 23:40 UTC, sydney-runkle commented on tests/test_type_alias_type.py
> +@pytest.mark.xfail(sys.version_info >= (3, 12), reason="TypeAliasType doesn't have __qualname__ yet")
Based on the changes in #7929, I think you can remove this xfail marker

2023-10-26 19:05 UTC, sydney-runkle approved these changes
@alexdrydew,

Thanks for the contribution 🌟 ! Looks great.

2023-10-26 19:14 UTC, merged