refactor: use pre 3.10 style annotations for ConfigDict
pydantic/pydantic pull request #8137
Opened 2023-11-15 15:19 UTC by waterfountain1996

## Change Summary

Rewrite `pydantic.ConfigDict` with pre 3.10 style annotations (e.g using `typing.Union` instead of `|`)

## Related issue number

Fixes #8134 

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [x] Unit tests for the changes exist
* [x] Tests pass on CI
* [x] Documentation reflects the changes where applicable
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

2023-11-15 15:21 UTC, waterfountain1996 commented
Not sure if file-level `# ruff: noqa: ...` is the best way to suppress the linter errors, but I'm sure that we can't set project-wide setting to ignore typing upgrades since I saw that a lot of function signatures use `|`-style annotations by grepping the files.

please review

2023-11-15 15:50 UTC, sydney-runkle requested changes
The changes to `pydantic/config.py` look good overall!

Please fix the broken tests + add a new test verifying that things work for your use case 😄. Thanks for the contribution! 🚀

2023-11-16 06:34 UTC, waterfountain1996 commented
@sydney-runkle 
I'm afraid it's not possible to use ConfigDict as annotation because of the circular import between it and `pydantic/_internal/_generate_schema.py`, which resolves the type annotations. I've tried a few things and I either got an error saying that there's no `_GenerateSchema` (which is imported by `ConfigDict` if `TYPE_CHECKING`) or that the model is incomplete and I should rebuild it

2023-11-16 14:56 UTC, sydney-runkle commented
@waterfountain1996,

Ah, that makes sense. I'll go ahead and close this PR then. Thanks for looking into this thoroughly!! 🌟

2023-11-16 14:56 UTC, closed without merging