Add a `with_config` decorator to comply with typing spec
pydantic/pydantic pull request #8611
Opened 2024-01-23 16:05 UTC by Viicos

May fix https://github.com/pydantic/pydantic/issues/8514, as suggested in a comment.

If accepted, better documentation will follow

2024-01-23 23:45 UTC, sydney-runkle requested changes
Hey @Viicos,

@dmontagu and I really like this approach. A few notes:

It'd be great if this could also be used with dataclasses. I think as it stands, it can, but you just haven't documented it yet. A few requests for changes (I know you wanted to get this approved before working on additional docs):

1. Docs update with a vanilla example for both `dataclass` and `TypedDict`. Docs in both the "Concepts" section and "API Documentation" section (via docstrings) would be fantastic.
2. `mypy` tests with this new decorator, as a proof of concept for how this fixes the original issue.

Thanks a bunch for your work on this - it'll be a great feature to have :).

2024-01-24 08:00 UTC, Viicos commented
> It'd be great if this could also be used with dataclasses.

By `dataclass`, do you mean the Pydantic one or stdlib? If it is Pydantic dataclasses, I think it would add confusion as:
- using `@dataclass(config=ConfigDict(...))` already works, and I don't see any benefit of using `@with_config` instead (but I might be missing something?)
- Users would have to be careful about the order between `@dataclass` and `@with_config`:
```python
from pydantic import with_config
from pydantic.dataclasses import dataclass

@with_config(ConfigDict(...))  # Will not work, config is already configured by the `@dataclass` decorator below
@dataclass
class Foo:
    ...
```

2024-01-24 08:44 UTC, Viicos commented
Please review

2024-01-24 13:37 UTC, sydney-runkle requested changes
@Viicos,

Changes look great. I've requested two small docs updates. Additionally, looks like the `mypy` test isn't working properly. Could you please update that when you have a chance?

Other than that, looks good to go! Thanks!

2024-01-25 21:40 UTC, sydney-runkle commented
@Viicos,

I've moved the attached issue into the 2.7.0 milestone :).

2024-01-26 13:26 UTC, sydney-runkle commented
@Viicos,

Amazing work 🚀. Merging this now to be included in 2.7.0!

2024-01-26 13:26 UTC, sydney-runkle approved these changes

2024-01-26 13:26 UTC, merged