Fix inheriting annotations in dataclasses
pydantic/pydantic pull request #8679
Opened 2024-01-30 13:29 UTC by sydney-runkle

## Change Summary

Dataclass inheritance bug introduced in https://github.com/pydantic/pydantic/commit/2e459bb563dbc296c2bcffbfd1a3caf21241b8e0, being fixed here.

## Related issue number

Fix https://github.com/pydantic/pydantic/issues/8670

## Checklist

* [ ] The pull request title is a good summary of the changes - it will be used in the changelog
* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI
* [ ] Documentation reflects the changes where applicable
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

2024-01-30 13:46 UTC, sydney-runkle commented
Please review

2024-01-30 16:28 UTC, alexmojaki commented on pydantic/dataclasses.py
> +        for annotation_cls in cls.__mro__[::-1]:
why reversed? that seems wrong

2024-01-30 16:30 UTC, alexmojaki requested changes
Please also test using the same field name with different type annotations - I think reversing the `__mro__` will break that test.

2024-02-01 12:38 UTC, alexmojaki commented on tests/test_dataclasses.py
> +    c = C(a='a', b='b', c='c', d='d')
Now that all classes are decorated, I think you can go back to checking both B and C in a loop, and then the previous test can be removed.

2024-02-01 13:51 UTC, alexmojaki approved these changes
Thanks!

2024-02-01 13:55 UTC, merged