Allow an optional separator splitting the value and unit of the result of `ByteSize.human_readable`.
pydantic/pydantic pull request #8706
Opened 2024-02-02 08:06 UTC by jks15satoshi

## Change Summary

Allow splitting the value and unit of the result of `ByteSize.human_readable` with a separator providing by the argument `separator`.

```python
>>> size = ByteSize(12345678)
>>> size.human_readable()
'11.8MiB'
>>> size.human_readable(separator=' ')
'11.8 MiB'
```

## Related issue number

fix #8668

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [x] Unit tests for the changes exist
* [x] Tests pass on CI
* [x] Documentation reflects the changes where applicable
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

Selected Reviewer: @adriangb

2024-02-02 08:15 UTC, jks15satoshi commented
Please review

2024-02-02 20:57 UTC, sydney-runkle requested changes
@jks15satoshi,

I think it'd make more sense to support a `str` type separator, which is an empty string by default. Could you please use that approach instead?

Thanks for your work here. Looking forward to having this new feature.

2024-02-03 00:45 UTC, jks15satoshi commented
> @jks15satoshi,
> 
> I think it'd make more sense to support a `str` type separator, which is an empty string by default. Could you please use that approach instead?
> 
> Thanks for your work here. Looking forward to having this new feature.

OK. Changes committed.

2024-02-06 13:55 UTC, sydney-runkle commented on pydantic/types.py
> +            separator: Split the value and unit with a specific separator.
```suggestion
            separator: A string used to split the value and unit. Defaults to an empty string ('').
```

2024-02-06 14:05 UTC, sydney-runkle approved these changes
Looks great, thanks! So excited to have this as a new feature in our upcoming minor release :).

2024-02-06 14:05 UTC, merged

2024-02-06 14:08 UTC, jks15satoshi commented
> Looks great, thanks! So excited to have this as a new feature in our upcoming minor release :).

Thanks so much! It's my pleasure.