Fix serialization of NameEmail if name includes an email address
pydantic/pydantic pull request #8860
Opened 2024-02-20 22:03 UTC by NeevCohen

## Change Summary

Fixing a serialization issue where an email would include an email address in the name i.e. `"name@gmail.com" <name@gmail.com>` and `NameEmail` would validate it correctly but remove the quotes when serializing back into a string

```python
import json
from pydantic import BaseModel, NameEmail

class Email(BaseModel):
  From: NameEmail

email = Email(From='"name@mailbox.com" <name@mailbox.com>')
print(email)
# output
# From=NameEmail(name='name@mailbox.com', email='name@mailbox.com')

obj = json.loads(email.model_dump_json())
print(obj)
# output
# {'From': 'name@mailbox.com <name@mailbox.com>'}

email = Email(From=obj['From'])
# Traceback (most recent call last):
#  ...
#    email = Email(From=obj['From'])
#            ^^^^^^^^^^^^^^^^^^^^^^^
#  File "/<some_path>/lib/python3.11/site-packages/pydantic/main.py", line 171, in __init__
#    self.__pydantic_validator__.validate_python(data, self_instance=self) pydantic_core._pydantic_core.ValidationError: 1 validation error for Email From
#  value is not a valid email address: The email address is not valid. It must have exactly one @-sign. [type=value_error, input_value='name@mailbox.com <name@mailbox.com>', input_type=str]
```

## Related issue number

Fixing #8811 

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [x] Unit tests for the changes exist
* [x] Tests pass on CI
* [x] Documentation reflects the changes where applicable
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

2024-02-20 22:13 UTC, NeevCohen commented
Please review

2024-02-20 23:41 UTC, sydney-runkle commented
@NeevCohen,

Thanks for the PR. I will confirm with the team tomorrow if this is the approach we want to take for the fix, and I'll get back to you early tomorrow :).

2024-02-21 14:04 UTC, sydney-runkle commented
@NeevCohen,

Let's go with a more simple approach of simply checking for an @ symbol in the name :).

2024-02-22 13:48 UTC, sydney-runkle requested changes
As mentioned in my above comment, let's go with a simple check for `@` instead of the regex matching. Thanks!

2024-02-22 13:59 UTC, NeevCohen commented
@sydney-runkle sure, once I'll get home I'll change it

2024-02-23 10:31 UTC, NeevCohen commented
@sydney-runkle Changed it as per your comment

2024-02-23 12:29 UTC, sydney-runkle approved these changes
Looks great, thanks!!

2024-02-23 12:29 UTC, merged