Add `Config.val_json_bytes`
pydantic/pydantic pull request #9770
Opened 2024-06-26 23:08 UTC by josh-newman

## Change Summary

Update `Config` with new option added in pydantic/pydantic-core#1308.

## Related issue number

None.

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [x] Unit tests for the changes exist
* [ ] Tests pass on CI
* [ ] Documentation reflects the changes where applicable
* [ ] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

2024-06-28 17:27 UTC, sydney-runkle reviewed
Looks great! You can use a specific `xfail` reason argument instead of a comment above :).

We can go ahead and merge this before the corresponding `pydantic-core` release is out, but could you please provide a screenshot that these tests are passing locally with your branch of `pydantic-core`?

2024-06-28 17:27 UTC, sydney-runkle commented on tests/test_json.py
> +@pytest.mark.xfail
```suggestion
@pytest.mark.xfail(reason='<something about pydantic-core upgrade>')
```

2024-06-28 17:28 UTC, sydney-runkle commented
Let's add the changes in https://github.com/pydantic/pydantic/pull/9772 to this PR as well :). Thanks!

2024-07-06 00:59 UTC, josh-newman commented
Thanks @sydney-runkle, I've updated the xfail reasons and run tests at pydantic/pydantic-core#1308's HEAD:
<img width="1920" alt="Screenshot 2024-07-05 at 17 53 35" src="https://github.com/pydantic/pydantic/assets/3987603/100493cb-d2fe-497a-aa27-7e175c7b46a7">

When pydantic/pydantic-core#1308 is incorporated, cherry-picking d7b2fd292166fe67b547cd2ca83cc55818eeb15b should fix the tests.

2024-07-18 19:11 UTC, sydney-runkle commented
Just provided some feedback on https://github.com/pydantic/pydantic-core/pull/1308#pullrequestreview-2186661660, thanks for your work here @josh-newman!

2024-07-18 19:12 UTC, sydney-runkle requested changes
Awesome work! Just a quick note on the docs

2024-07-18 19:14 UTC, sydney-runkle commented
Awesome job on getting the tests to pass locally.

> We can go ahead and merge this before the corresponding pydantic-core release is out, but could you please provide a screenshot that these tests are passing locally with your branch of pydantic-core?

I realize, I want to walk this back just a bit - given that this is a new feature and not a bug fix, we'll want to wait for a release. That being said, I can do a minor release of `pydantic-core` once we get your core PR in (should be quite soon), then immediately merge this one as well.

Sorry for the delay on my review, was out for a long holiday. We're super excited about this new feature and your great work!

2024-07-18 19:14 UTC, sydney-runkle commented
^^ That being said, I'm not worried about the integration tests failing on the `pydantic-core` end, we can merge that despite the failures knowing that things are working end to end locally.

2024-07-18 19:17 UTC, sydney-runkle commented
> I realize, I want to walk this back just a bit - given that this is a new feature and not a bug fix, we'll want to wait for a release. That being said, I can do a minor release of pydantic-core once we get your core PR in (should be quite soon), then immediately merge this one as well.

To elaborate a bit more, in case others are curious in the future: merging this into main would result in new docs being added to our `latest` page that were a bit inaccurate, as said features wouldn't yet be available. Thus, I think it makes more sense to wait. It's a bit of an awkward dance with things not in one repo, but we definitely appreciate having the PRs open in both `pydantic` and `pydantic-core` so that we can see what upstream changes look like.

2024-07-25 22:14 UTC, josh-newman commented on docs/errors/validation_errors.md
> +This error is raised when a `bytes` value is valid under the configured encoding:
Thanks, done!

2024-07-30 15:42 UTC, sydney-runkle approved these changes
Looks good, will wait to merge until we pull the `pydantic-core` changes in 👍

2024-08-06 01:27 UTC, merged

2024-08-06 01:31 UTC, sydney-runkle commented
Awesome work! Merged into main 🥳 !

2024-08-06 17:29 UTC, josh-newman commented
Thanks for the reviews!