Add support for ZoneInfo
pydantic/pydantic pull request #9896
Opened 2024-07-15 11:00 UTC by Youssefares

## Change Summary

## Related issue number
fix #4710 

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [x] Unit tests for the changes exist
* [ ] Tests pass on CI
* [x] Documentation reflects the changes where applicable
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

2024-07-15 11:10 UTC, yezz123 commented
hey @Youssefares correct me if i'm wrong but i guess its similar to this one we have in Pydantic-extra https://github.com/pydantic/pydantic-extra-types/pull/193

2024-07-15 11:19 UTC, Youssefares commented
> hey @Youssefares correct me if i'm wrong but i guess its similar to this one we have in Pydantic-extra [pydantic/pydantic-extra-types#193](https://github.com/pydantic/pydantic-extra-types/pull/193)

This does seem very similar, zoneinfo.ZoneInfo is part of the python std library though. I maybe wrong but my understanding of pydantic-extra-types is that it defines additional convenience types, while pydantic itself is where we offer support for standard types. I am not 100% sure about the need for an extra-type in this scenario given zoneinfo now exists since 3.9.

I'll leave to maintainers to decide whether the extra type using pytz is still required, but I believe supporting zoneinfo is very much worthwhile eitherway.

2024-07-15 11:37 UTC, yezz123 commented
> > hey @Youssefares correct me if i'm wrong but i guess its similar to this one we have in Pydantic-extra [pydantic/pydantic-extra-types#193](https://github.com/pydantic/pydantic-extra-types/pull/193)
> 
> This does seem very similar, zoneinfo.ZoneInfo is part of the python std library though. I maybe wrong but my understanding of pydantic-extra-types is that it defines additional convenience types, while pydantic itself is where we offer support for standard types. I am not 100% sure about the need for an extra-type in this scenario given zoneinfo now exists since 3.9. I also think (in my experience at least), most people try to drop the pytz dependency from their project nowadays if zoneinfo does the job.
> 
> I'll leave to maintainers to decide whether the extra type using pytz is still required, but I believe supporting zoneinfo is very much worthwhile eitherway.

Yes as you said the best answer we can have is from maintainers themselves.

cc @sydney-runkle @samuelcolvin

2024-07-15 14:28 UTC, Youssefares commented
please review

2024-07-18 19:46 UTC, sydney-runkle commented
Exciting stuff here - this is next in my queue to review :). Should be able to get to it this evening or first thing tomorrow :).

2024-07-22 15:02 UTC, sydney-runkle requested changes
Very excited to include this. Added one minor simplification request!

2024-07-22 15:02 UTC, sydney-runkle commented on pydantic/_internal/_generate_schema.py
> +            serialization=ser,
`core_schema.to_string_ser_schema()`

2024-07-22 15:03 UTC, sydney-runkle commented
> I'll leave to maintainers to decide whether the extra type using pytz is still required, but I believe supporting zoneinfo is very much worthwhile eitherway.

I think we should definitely just stick to std lib support, so the zoneinfo addition here is great!

2024-07-24 11:34 UTC, Youssefares commented
CI's failing because this issue #9761 been resurrected somehow it seems? Looking into it..

2024-07-24 11:53 UTC, Youssefares commented
That look better.. 🟢 ✅

2024-07-24 11:54 UTC, Youssefares commented on pydantic/_internal/_generate_schema.py
> +            serialization=ser,
Thanks! I've addressed this.

2024-07-24 13:29 UTC, sydney-runkle approved these changes
Looks great!

Thanks a bunch!

2024-07-24 13:29 UTC, merged