Fix false positives on v1 models in mypy plugin for from_orm check requiring from_attributes=True config
pydantic/pydantic pull request #9938
Opened 2024-07-22 17:04 UTC by radekwlsk

## Change Summary

This is a fix for bug reported in #9936 when using both v1 and v2 for migration period with `pydantic.mypy` plugin enabled the `"<ModelName>" does not have from_attributes=True  [pydantic-orm]` error is getting raised for `pydantic.v1.BaseModel` models that should not be checked by `pydantic.mypy` plugin (that is supposed to work on current - v2 - pydantic).

Note that test will fail unless the other bug with `@typing_extensions.deprecated` decorator mentioned in #9936 is fixed.

## Related issue number

fix #9936

## Checklist

* [x] The pull request title is a good summary of the changes - it will be used in the changelog
* [x] Unit tests for the changes exist
* [ ] Tests pass on CI
* [x] Documentation reflects the changes where applicable
* [x] My PR is ready to review, **please add a comment including the phrase "please review" to assign reviewers**

2024-07-22 17:48 UTC, dmontagu commented on tests/mypy/outputs/1.0.1/pyproject-plugin_toml/from_orm_v1_noconflict.py
I think you don't need the copies of this file for each subsequent version if they are all the same — it will reuse the older version file for newer versions of mypy. So basically I think we can delete the copy of this file for v1.1.1, v1.2.0, and v1.4.1 from this MR and the tests should still pass.

2024-07-22 17:50 UTC, dmontagu requested changes
This looks good to me, other than — can we try removing the duplicates of the `from_orm_v1_noconflict.py` file so we only keep the one in the `1.0.1` folder? I think that will still pass CI since it seems there are no changes in the subsequent versions.

2024-07-22 17:57 UTC, dmontagu commented
Unfortunately it seems that it may be difficult to resolve the issue with deprecated, as I think mypy doesn't have a way for plugins to override the behavior of decorated methods. I might be misinterpreting something, but it seems that https://github.com/python/mypy/issues/9915 might be necessary to achieve this (not sure).

I think there are things we could do to avoid the decorator affecting the plugin behavior, but I would expect that to get in the way of some desirable errors produced by calling deprecated methods. So I'm not sure what's best here

2024-07-23 07:07 UTC, radekwlsk commented on tests/mypy/outputs/1.0.1/pyproject-plugin_toml/from_orm_v1_noconflict.py
Removed.

2024-07-23 07:08 UTC, radekwlsk commented
@dmontagu  Thanks for the review, removed the duplicate result files. For the decorator I have no clue how to approach it without breaking the deprecation warning either.

One way to "resolve" it would be to focus the unit of test on not raising "pydantic-orm" error for `v1.BaseModel` and skip the case for raising it where expected. WDYT?

2024-07-23 07:35 UTC, radekwlsk commented
> This looks good to me, other than — can we try removing the duplicates of the `from_orm_v1_noconflict.py` file so we only keep the one in the `1.0.1` folder? I think that will still pass CI since it seems there are no changes in the subsequent versions.

CI passes as expected, thanks.

2024-07-25 07:50 UTC, radekwlsk commented
@dmontagu Please re-review. Is there a hope to get this fix included in a 2.8 patch release without waiting for 2.9 rollout?

2024-07-30 11:38 UTC, radekwlsk commented
Please review
It is stuck in waiting for review for over a week now 😞

2024-07-30 12:45 UTC, sydney-runkle commented
@radekwlsk,

Thanks for the ping. I messaged @dmontagu and we'll take a look shortly!

2024-07-30 20:13 UTC, dmontagu commented on tests/mypy/outputs/1.0.1/pyproject-plugin_toml/from_orm_v1_noconflict.py
I think you shouldn’t need this file at all if there are no mypy errors produced

2024-07-30 20:28 UTC, dmontagu approved these changes

2024-07-31 10:05 UTC, merged

2024-08-01 12:24 UTC, radekwlsk commented
@sydney-runkle Are you able to provide any timeline for release containing that fix?

2024-08-01 14:23 UTC, sydney-runkle commented
@radekwlsk,

Was planning on releasing this with v2.9 in late August!

2024-08-01 15:11 UTC, radekwlsk commented
So I guess I shouldn't wait for `2.8.3` with bugfixes? Thanks, I'll fork-patch mypy plugin locally for the time being.

2024-08-01 19:19 UTC, sydney-runkle commented
Right, I don't think we're in a rush for a v2.8.3 at the moment, but I'll keep you updated!